services:
  hoehoetvhs_dev_bot:
    build: .
    container_name: hoehoetvhs_dev_bot
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Seoul
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./config.js:/bot/config.js
      - ./logs:/bot/logs