services:
  hoeng-bot:
    image: ghcr.io/hoehoetvhss/hoeng-bot:latest
    container_name: hoeng-bot
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Seoul
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./config.js:/bot/config.js
      - ./views/dashboard.html:/bot/views/dashboard.html
      - ./logs:/bot/logs